name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - dev # Added for CIPP's development branch
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

env:
  APP_LOCATION: "/" # Root of the React app (adjust if in a subdirectory, e.g., "src")
  API_LOCATION: "" # Leave empty as CIPP-API is deployed separately
  OUTPUT_LOCATION: "build" # Output directory after `npm run build`
  AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_SMOKE_0BF381E0F }}

permissions:
  contents: read
  pull-requests: write # For PR comments

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use Node.js version compatible with CIPP (e.g., 20.x)

      - name: Install Dependencies
        run: npm ci # Cleaner, reproducible installs

      - name: Build App
        run: npm run build # Builds the React app, outputs to "build" folder

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          ###### Repository/Build Configurations ######
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
